-- 知識學院 RPG｜Supabase 初始資料表
-- 建議在 Supabase SQL Editor 執行。
-- 注意：正式上線前仍應先用測試帳號確認 RLS 是否符合你的需求。

create table if not exists public.player_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null,
  grade_level int not null default 1 check (grade_level between 1 and 7),
  grade_percent int not null default 0 check (grade_percent between 0 and 100),
  exp bigint not null default 0,
  coins bigint not null default 0,
  achievement_points bigint not null default 0,
  equipped_hair text,
  equipped_head text,
  equipped_body text,
  equipped_weapon text,
  equipped_accessory text,
  equipped_pet text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.game_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  grade int not null,
  subject text not null,
  unit_id text not null,
  score int not null default 0,
  first_correct_rate int not null default 0,
  final_correct_rate int not null default 0,
  exp_earned int not null default 0,
  coins_earned int not null default 0,
  boss boolean not null default false,
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.boss_tickets (
  user_id uuid not null references auth.users(id) on delete cascade,
  grade int not null,
  subject text not null,
  amount int not null default 0 check (amount >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, grade, subject)
);

create table if not exists public.player_achievements (
  user_id uuid not null references auth.users(id) on delete cascade,
  achievement_id text not null,
  points int not null default 0,
  unlocked_at timestamptz not null default now(),
  primary key (user_id, achievement_id)
);

alter table public.player_profiles enable row level security;
alter table public.game_results enable row level security;
alter table public.boss_tickets enable row level security;
alter table public.player_achievements enable row level security;

-- player_profiles：所有登入玩家可讀排行榜所需資料；只能修改自己的資料。
drop policy if exists "profiles readable by authenticated users" on public.player_profiles;
create policy "profiles readable by authenticated users"
on public.player_profiles for select
to authenticated
using (true);

drop policy if exists "players insert own profile" on public.player_profiles;
create policy "players insert own profile"
on public.player_profiles for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "players update own profile" on public.player_profiles;
create policy "players update own profile"
on public.player_profiles for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- game_results：玩家可新增自己的紀錄，也可讀取登入玩家的成績做排行榜。
drop policy if exists "results readable by authenticated users" on public.game_results;
create policy "results readable by authenticated users"
on public.game_results for select
to authenticated
using (true);

drop policy if exists "players insert own results" on public.game_results;
create policy "players insert own results"
on public.game_results for insert
to authenticated
with check (auth.uid() = user_id);

-- boss_tickets：只能讀寫自己的票。
drop policy if exists "players read own tickets" on public.boss_tickets;
create policy "players read own tickets"
on public.boss_tickets for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "players insert own tickets" on public.boss_tickets;
create policy "players insert own tickets"
on public.boss_tickets for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "players update own tickets" on public.boss_tickets;
create policy "players update own tickets"
on public.boss_tickets for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- achievements：自己的成就可寫；登入玩家可讀作成就榜。
drop policy if exists "achievements readable by authenticated users" on public.player_achievements;
create policy "achievements readable by authenticated users"
on public.player_achievements for select
to authenticated
using (true);

drop policy if exists "players insert own achievements" on public.player_achievements;
create policy "players insert own achievements"
on public.player_achievements for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "players update own achievements" on public.player_achievements;
create policy "players update own achievements"
on public.player_achievements for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
