-- 知識學院 RPG V3｜Supabase SQL
-- 先在 Supabase SQL Editor 執行本檔。

create table if not exists public.player_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  login_id text not null unique,
  nickname text not null,
  grade_level int not null default 1 check (grade_level between 1 and 7),
  grade_percent int not null default 0 check (grade_percent between 0 and 100),
  exp bigint not null default 0,
  coins bigint not null default 0,
  achievement_points bigint not null default 0,
  equipped_hair text,
  equipped_head text,
  equipped_body text,
  equipped_weapon text,
  equipped_accessory text,
  equipped_pet text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.game_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  grade int not null,
  subject text not null,
  unit_id text not null,
  score int not null default 0,
  first_correct_rate int not null default 0,
  final_correct_rate int not null default 0,
  exp_earned int not null default 0,
  coins_earned int not null default 0,
  boss boolean not null default false,
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.boss_tickets (
  user_id uuid not null references auth.users(id) on delete cascade,
  grade int not null,
  subject text not null,
  amount int not null default 0 check (amount >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_id,grade,subject)
);

create table if not exists public.unit_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  grade int not null,
  subject text not null,
  unit_id text not null,
  mastery int not null default 0 check (mastery between 0 and 100),
  updated_at timestamptz not null default now(),
  primary key (user_id,game_id)
);

create table if not exists public.player_achievements (
  user_id uuid not null references auth.users(id) on delete cascade,
  achievement_id text not null,
  points int not null default 0,
  unlocked_at timestamptz not null default now(),
  primary key (user_id,achievement_id)
);

alter table public.player_profiles enable row level security;
alter table public.game_results enable row level security;
alter table public.boss_tickets enable row level security;
alter table public.unit_progress enable row level security;
alter table public.player_achievements enable row level security;

-- 排行榜：登入者可讀 profile；自己可新增/修改。
drop policy if exists "profiles read" on public.player_profiles;
create policy "profiles read" on public.player_profiles for select to authenticated using (true);
drop policy if exists "profiles insert own" on public.player_profiles;
create policy "profiles insert own" on public.player_profiles for insert to authenticated with check (auth.uid()=user_id);
drop policy if exists "profiles update own" on public.player_profiles;
create policy "profiles update own" on public.player_profiles for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);

drop policy if exists "results read" on public.game_results;
create policy "results read" on public.game_results for select to authenticated using (true);
drop policy if exists "results insert own" on public.game_results;
create policy "results insert own" on public.game_results for insert to authenticated with check (auth.uid()=user_id);

drop policy if exists "tickets read own" on public.boss_tickets;
create policy "tickets read own" on public.boss_tickets for select to authenticated using (auth.uid()=user_id);
drop policy if exists "tickets insert own" on public.boss_tickets;
create policy "tickets insert own" on public.boss_tickets for insert to authenticated with check (auth.uid()=user_id);
drop policy if exists "tickets update own" on public.boss_tickets;
create policy "tickets update own" on public.boss_tickets for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);

drop policy if exists "progress read own" on public.unit_progress;
create policy "progress read own" on public.unit_progress for select to authenticated using (auth.uid()=user_id);
drop policy if exists "progress insert own" on public.unit_progress;
create policy "progress insert own" on public.unit_progress for insert to authenticated with check (auth.uid()=user_id);
drop policy if exists "progress update own" on public.unit_progress;
create policy "progress update own" on public.unit_progress for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);

drop policy if exists "achievements read" on public.player_achievements;
create policy "achievements read" on public.player_achievements for select to authenticated using (true);
drop policy if exists "achievements insert own" on public.player_achievements;
create policy "achievements insert own" on public.player_achievements for insert to authenticated with check (auth.uid()=user_id);
drop policy if exists "achievements update own" on public.player_achievements;
create policy "achievements update own" on public.player_achievements for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
